
package com.cmxv.webservices.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.cmxv.modellayer.DBentities.UserBase;
import com.cmxv.modellayer.DBentities.UserExt;
import com.cmxv.modellayer.DBentities.UserWithRights;
import com.cmxv.modellayer.collections.Users;
import com.oracle.xmlns.webservices.jaxws_databinding.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceWSDL", targetNamespace = "http://services.bussinesslayer.cmxv.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceWSDL {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/initRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.cmxv.bussinesslayer.services.UserBase
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserByLoginAndPassRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserByLoginAndPassResponse")
    public UserBase getUserByLoginAndPass(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/createOrUpdateRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/createOrUpdateResponse")
    public int createOrUpdate(
        @WebParam(name = "arg0", partName = "arg0")
        UserExt arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.cmxv.bussinesslayer.services.UserWithRights
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserWithRightsRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserWithRightsResponse")
    public UserWithRights getUserWithRights(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/deleteUserRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/deleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cmxv.bussinesslayer.services.UserExt
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserByIdRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getUserByIdResponse")
    public UserExt getUserById(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.cmxv.bussinesslayer.services.Users
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getAllUsersRequest", output = "http://services.bussinesslayer.cmxv.com/UserServiceWSDL/getAllUsersResponse")
    public Users getAllUsers();

}
