
package com.cmxv.webservices.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServiceWSDLService", targetNamespace = "http://services.bussinesslayer.cmxv.com/", wsdlLocation = "http://localhost:8080/EDMSWebLayer/user?wsdl")
public class UserServiceWSDLService
    extends Service
{

    private final static URL USERSERVICEWSDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSERVICEWSDLSERVICE_EXCEPTION;
    private final static QName USERSERVICEWSDLSERVICE_QNAME = new QName("http://services.bussinesslayer.cmxv.com/", "UserServiceWSDLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EDMSWebLayer/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICEWSDLSERVICE_WSDL_LOCATION = url;
        USERSERVICEWSDLSERVICE_EXCEPTION = e;
    }

    public UserServiceWSDLService() {
        super(__getWsdlLocation(), USERSERVICEWSDLSERVICE_QNAME);
    }

    public UserServiceWSDLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICEWSDLSERVICE_QNAME, features);
    }

    public UserServiceWSDLService(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICEWSDLSERVICE_QNAME);
    }

    public UserServiceWSDLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICEWSDLSERVICE_QNAME, features);
    }

    public UserServiceWSDLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceWSDLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceWSDL
     */
    @WebEndpoint(name = "UserServiceWSDLPort")
    public UserServiceWSDL getUserServiceWSDLPort() {
        return super.getPort(new QName("http://services.bussinesslayer.cmxv.com/", "UserServiceWSDLPort"), UserServiceWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceWSDL
     */
    @WebEndpoint(name = "UserServiceWSDLPort")
    public UserServiceWSDL getUserServiceWSDLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.bussinesslayer.cmxv.com/", "UserServiceWSDLPort"), UserServiceWSDL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICEWSDLSERVICE_EXCEPTION!= null) {
            throw USERSERVICEWSDLSERVICE_EXCEPTION;
        }
        return USERSERVICEWSDLSERVICE_WSDL_LOCATION;
    }

}
